# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28e159ade0146254631a613e9063368a974b02cc2fea9989e29a6deac17b23c8096fc4a637911c8d4305cfc6f958af0f755ff695163a8057b059354171c1c276

test:
  secret_key_base: a8a323cb80dfae4dd98f14c8a779d86e842c0bd3597997f7a87177c0017ed6ebbfeb50d1a0dc2ac285c5a00cc92b29cdd3c763336435bb5b513a3efa0ac4c762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
